sudo: required
language: generic
services:
  - docker



before_install:
  - docker build -t sstrool/docker-react -f Dockerfile.dev .

script:  
  - docker run -e CI=true sstrool/docker-react npm run test 